#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys
sys.path.append("/home/workspace/rqalpha")
from rqalpha.__main__ import entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(entry_point())
